"""empty message

Revision ID: 0d7ac51d923e
Revises: 43f1f673f87e
Create Date: 2024-11-19 17:56:02.871181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7ac51d923e'
down_revision: Union[str, None] = '43f1f673f87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vacancy', 'manager', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'manager_id')
    # ### end Alembic commands ###
