"""empty message

Revision ID: 4e009e356029
Revises: 0d7ac51d923e
Create Date: 2024-11-19 18:09:15.589859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e009e356029'
down_revision: Union[str, None] = '0d7ac51d923e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'manager', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='unique')
    op.drop_column('manager', 'telegram_id')
    # ### end Alembic commands ###
