"""empty message

Revision ID: 71b367fd89f6
Revises: cc687de9aea8
Create Date: 2024-11-17 17:54:09.000304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b367fd89f6'
down_revision: Union[str, None] = 'cc687de9aea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applicant', ['name'])
    op.create_unique_constraint(None, 'applicant', ['id'])
    op.create_unique_constraint(None, 'enterprise', ['name'])
    op.create_unique_constraint(None, 'enterprise', ['id'])
    op.create_unique_constraint(None, 'manager', ['name'])
    op.create_unique_constraint(None, 'manager', ['id'])
    op.create_unique_constraint(None, 'request', ['id'])
    op.create_unique_constraint(None, 'vacancy', ['enterprise_id'])
    op.create_unique_constraint(None, 'vacancy', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='unique')
    op.drop_constraint(None, 'vacancy', type_='unique')
    op.drop_constraint(None, 'request', type_='unique')
    op.drop_constraint(None, 'manager', type_='unique')
    op.drop_constraint(None, 'manager', type_='unique')
    op.drop_constraint(None, 'enterprise', type_='unique')
    op.drop_constraint(None, 'enterprise', type_='unique')
    op.drop_constraint(None, 'applicant', type_='unique')
    op.drop_constraint(None, 'applicant', type_='unique')
    # ### end Alembic commands ###
