"""empty message

Revision ID: d5e6eaf0519e
Revises: 71b367fd89f6
Create Date: 2024-11-17 20:18:36.021949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e6eaf0519e'
down_revision: Union[str, None] = '71b367fd89f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'applicant', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applicant', type_='unique')
    op.drop_column('applicant', 'telegram_id')
    # ### end Alembic commands ###
